// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAILPecCEWEcmbY9DmTrJzQtah_lXGhtZM',
    appId: '1:84563243352:web:9b15c77d803e2077ba752d',
    messagingSenderId: '84563243352',
    projectId: 'flutter-comerce-ad9e6',
    authDomain: 'flutter-comerce-ad9e6.firebaseapp.com',
    storageBucket: 'flutter-comerce-ad9e6.appspot.com',
    measurementId: 'G-FGPVY4DDJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdYCulp8DXSX1SjYDChvE4ZNj8rs5Qrg',
    appId: '1:84563243352:android:5759097c9e593abeba752d',
    messagingSenderId: '84563243352',
    projectId: 'flutter-comerce-ad9e6',
    storageBucket: 'flutter-comerce-ad9e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6XluCf3odM_KOd52_ouh8kEEUG7WQfE',
    appId: '1:84563243352:ios:f4fc2db6a5c201e4ba752d',
    messagingSenderId: '84563243352',
    projectId: 'flutter-comerce-ad9e6',
    storageBucket: 'flutter-comerce-ad9e6.appspot.com',
    iosBundleId: 'com.aarafrao.ecom.flutterCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc6XluCf3odM_KOd52_ouh8kEEUG7WQfE',
    appId: '1:84563243352:ios:f4fc2db6a5c201e4ba752d',
    messagingSenderId: '84563243352',
    projectId: 'flutter-comerce-ad9e6',
    storageBucket: 'flutter-comerce-ad9e6.appspot.com',
    iosBundleId: 'com.aarafrao.ecom.flutterCommerce',
  );
}
